export const SHORT_TERM_SURCHARGE_CANCELATION = 1.5 //50%
export const SHORT_TERM_SURCHARGE_SPORT = 1.3 //30%

export const LONG_TERM_SURCHARGE_CANCELATION = 1.2 //20%
export const LONG_TERM_SURCHARGE_SPORT = 1.1 //10%

export const BASIC_PACKAGE_PRICE_PER_DAY = 1.2
export const MEDIUM_PACKAGE_PRICE_PER_DAY = 1.8
export const EXTRA_PACKAGE_PRICE_PER_DAY = 2.4

export const BASIC_PACKAGE_PRICE_PER_YEAR = 39
export const MEDIUM_PACKAGE_PRICE_PER_YEAR = 49
export const EXTRA_PACKAGE_PRICE_PER_YEAR = 59
